//
// Generated by Lincoln on: 2018.05.15 at 12:42:33 AM CEST
//

package utilities;

import collections.Candidacies;
import models.Candidacy;
import models.Candidate;
import models.Convention;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the utilities package. 
 * <p>An CandidacyFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class CandidacyFactory {

    private final static QName _Candidate_QNAME = new QName("", "candidate");
    private final static QName _Candidacy_QNAME = new QName("", "candidacy");

    /**
     * Create a new CandidacyFactory that can be used to create new instances of schema derived classes for package: utilities
     * 
     */
    public CandidacyFactory() {
    }

    /**
     * Create an instance of {@link Convention }
     * 
     */
    public Convention createConvention() {
        return new Convention();
    }

    /**
     * Create an instance of {@link Candidate }
     * 
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link Candidacy }
     * 
     */
    public Candidacy createCandidacy() {
        return new Candidacy();
    }

    /**
     * Create an instance of {@link Candidacies }
     * 
     */
    public Candidacies createCandidacies() {
        return new Candidacies();
    }

    /**
     * Create an instance of {@link Convention.Positions }
     * 
     */
    public Convention.Positions createConventionPositions() {
        return new Convention.Positions();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Candidate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "candidate")
    public JAXBElement<Candidate> createCandidate(Candidate value) {
        return new JAXBElement<Candidate>(_Candidate_QNAME, Candidate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Candidacy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "candidacy")
    public JAXBElement<Candidacy> createCandidacy(Candidacy value) {
        return new JAXBElement<Candidacy>(_Candidacy_QNAME, Candidacy.class, null, value);
    }

}
