//
// Generated by Lincoln on: 2018.05.15 at 12:41:17 AM CEST
//

package utilities;

import collections.Conventions;
import models.Convention;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the utilities package. 
 * <p>An ConventionFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ConventionFactory {


    /**
     * Create a new ConventionFactory that can be used to create new instances of schema derived classes for package: utilities
     * 
     */
    public ConventionFactory() {
    }

    /**
     * Create an instance of {@link Convention }
     * 
     */
    public Convention createConvention() {
        return new Convention();
    }

    /**
     * Create an instance of {@link Conventions }
     * 
     */
    public Conventions createConventions() {
        return new Conventions();
    }

    /**
     * Create an instance of {@link Convention.Positions }
     * 
     */
    public Convention.Positions createConventionPositions() {
        return new Convention.Positions();
    }

}
