//
// Generated by Lincoln on: 2018.05.15 at 12:41:17 AM CEST
//

package models;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Convention complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "convention", propOrder = {"label", "detail", "scheduled", "place", "image", "positions"})
public class Convention {

    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    protected String detail;
    @XmlElement(required = true)
    protected String scheduled;
    @XmlElement(required = true)
    protected String place;
    @XmlElement(required = true)
    protected String image;
    @XmlElement(required = true)
    protected Convention.Positions positions;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetail(String value) {
        this.detail = value;
    }

    /**
     * Gets the value of the scheduled property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getScheduled() {
        return scheduled;
    }
    
    /** 
     * Gets if the convention isn't already done
     * 
     * @return boolean
     * 
     */
    public boolean getActive() {
    	boolean b = true;
		try {
	    	Date datejour = new Date();
	    	SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
	    	Date format;
			format = formatter.parse(scheduled);
			b=datejour.before(format);
		} catch (ParseException e) {
			e.printStackTrace();
		}
    	return b;
    }

    /**
     * Sets the value of the scheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduled(String value) {
        this.scheduled = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the positions property.
     * 
     * @return
     *     possible object is
     *     {@link Convention.Positions }
     *     
     */
    public Convention.Positions getPositions() {
        return positions;
    }

    /**
     * Sets the value of the positions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Convention.Positions }
     *     
     */
    public void setPositions(Convention.Positions value) {
        this.positions = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Convention)) return false;
        Convention that = (Convention) o;
        return Objects.equals(label, that.label) &&
                Objects.equals(detail, that.detail) &&
                Objects.equals(scheduled, that.scheduled) &&
                Objects.equals(place, that.place) &&
                Objects.equals(image, that.image) &&
                Objects.equals(positions, that.positions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(label, detail, scheduled, place, image, positions);
    }

    @Override
    public String toString() {
        return "Convention{" +
                "label='" + label + '\'' +
                ", detail='" + detail + '\'' +
                ", scheduled=" + scheduled +
                ", place='" + place + '\'' +
                ", image='" + image + '\'' +
                ", positions=" + positions +
                '}';
    }

    /**
     * <p>Java class for Positions complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"position"})
    public static class Positions {

        @XmlElement(required = true)
        protected List<String> position;

        /**
         * Gets the value of the position property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the position property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPosition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPosition() {
            if (position == null) {
                position = new ArrayList<String>();
            }
            return this.position;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Positions)) return false;
            Positions positions = (Positions) o;
            return Objects.equals(position, positions.position);
        }

        @Override
        public int hashCode() {
            return Objects.hash(position);
        }

        @Override
        public String toString() {
            return "Positions{" +
                    "position=" + position +
                    '}';
        }
    }
}
